apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: org1
spec:
  project: default
  source:
    repoURL: https://github.com/el7-7/poc-gitops-testsite.git
    targetRevision: main
    path: apps/fail-test
  destination:
    server: https://kubernetes.default.svc
    namespace: org1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
