apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-org1
  namespace: argocd
  
  annotations:
  # ✅ Sync success → Slack channel
  notifications.argoproj.io/subscribe.on-sync-succeeded.slack: wordpress-org1

  # 🚨 Sync failure → alerts channel (recommended)
  notifications.argoproj.io/subscribe.on-sync-failed.slack: wordpress-alerts

  # ⚠️ Optional: health degraded alerts
  notifications.argoproj.io/subscribe.on-health-degraded.slack: wordpress-alerts

spec:
  project: wordpress-org1

  sources:
    # 1. Helm chart
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: wordpress
      targetRevision: 30.0.4
      helm:
        valueFiles:
          - $values/apps/wordpress-org1/values.yaml
  
    # 2. Values repo (keep ref!)
    - repoURL: https://github.com/el7-7/poc-gitops-testsite.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: org1

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
